model:
  base_learning_rate: 3.0e-5  
  target: sgm.models.diffusion.DiffusionEngine
  params:
    input_key: latents
    no_log_keys: [audio_emb, fps_id, motion_bucket_id, cond_aug]
    scale_factor: 0.18215
    disable_first_stage_autocast: True
    ckpt_path: checkpoints/svd.safetensors
    compile_model: False

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.DiscreteDenoiser
      params:
        num_idx: 1000

        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.EpsScaling
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization

    network_config:
      target: sgm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
          # - is_trainable: False
          #   input_key: txt
          #   target: sgm.modules.encoders.modules.FrozenOpenCLIPEmbedder
          #   params:
          #     freeze: true
          #     layer: penultimate

          - is_trainable: False
          input_key: cond_frames_without_noise
          target: sgm.modules.encoders.modules.FrozenOpenCLIPImagePredictionEmbedder
          params:
            n_cond_frames: 1
            n_copies: 1
            open_clip_embedding_config:
              target: sgm.modules.encoders.modules.FrozenOpenCLIPImageEmbedder
              params:
                freeze: True

          - input_key: cond_frames
          is_trainable: False
          target: sgm.modules.encoders.modules.VideoPredictionEmbedderWithEncoder
          params:
            disable_encoder_autocast: True
            n_cond_frames: 1
            n_copies: 1
            is_ae: True
            encoder_config:
              target: sgm.models.autoencoder.AutoencoderKLModeOnly
              params:
                embed_dim: 4
                monitor: val/rec_loss
                ddconfig:
                  attn_type: vanilla-xformers
                  double_z: True
                  z_channels: 4
                  resolution: 256
                  in_channels: 3
                  out_ch: 3
                  ch: 128
                  ch_mult: [1, 2, 4, 4]
                  num_res_blocks: 2
                  attn_resolutions: []
                  dropout: 0.0
                lossconfig:
                  target: torch.nn.Identity

    first_stage_config:
      target: sgm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss
      params:        
        batch2model_keys:
          - image_only_indicator
          - num_video_frames
        loss_weighting_config:
          target: sgm.modules.diffusionmodules.loss_weighting.EpsWeighting
        sigma_sampler_config:
          target: sgm.modules.diffusionmodules.sigma_sampling.EDMSampling
          params:
            p_mean: 0.7
            p_std: 1.6

data:
  target: sgm.data.video_datamodule_latent.VideoDataModule
  params:
    train:
      datapipeline:
        filelist: /fsx/rs2517/data/lists/HDTF/filelist_videos_train.txt
        resize_size: 512
        audio_folder: audio
        video_folder: cropped_videos_original
        video_extension: .mp4
        audio_extension: .wav
        audio_rate: 16000
        num_frames: 14
        need_cond: False
        mode: prediction
        use_latent: True
        latent_type: video
        latent_scale: 1  # For backwards compatibility
        from_audio_embedding: True
        load_all_possible_indexes: True
        audio_emb_type: whisper
        # cond_noise: [-3.0, 0.5]
        cond_noise: 0.
        motion_id: 60
        data_mean: null
        data_std: null

      loader:
        batch_size: 1
        num_workers: 6
        drop_last: True
        pin_memory: True
        persistent_workers: True

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
      save_top_k: 1

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 25000

    video_logger:
      target: sgm.callbacks.video_logger.VideoLogger
      params:
        disabled: False
        enable_autocast: False
        batch_frequency: 1000
        max_videos: 2
        increase_log_steps: False
        log_first_step: True
        log_videos_kwargs:
          use_ema_scope: False
          N: 2
          n_rows: 1

  trainer:
    devices: 7,
    benchmark: False
    num_sanity_val_steps: 1
    accumulate_grad_batches: 1
    max_epochs: 1000
    precision: 16