defaults:
  - base_data

filelist: /fsx/rs2517/data/lists/voxceleb2_proper.txt
audio_folder: audio
video_folder: cropped_videos_original
video_extension: .mp4
audio_extension: .wav
latent_folder: null

dataset_name: vox


video_path: /fsx/behavioural_computing_data/voxceleb2
audio_emb: /fsx/rs2517/data/voxceleb2_wav2vec2_feats
latents: /fsx/rs2517/data/voxceleb2_sd_latent
/fsx/behavioural_computing_data/voxceleb2/test/