model:
  base_learning_rate: 3.e-5
  target: sgm.models.diffusion.DiffusionEngine
  params:
    input_key: latents
    scale_factor: 0.18215
    disable_first_stage_autocast: True
    ckpt_path: logs/2024-07-29T15-36-01_example_training-svd_image_reference_land/checkpoints/last.ckpt/checkpoint/mp_rank_00_model_states.pt
    # remove_keys_from_weights: [model.diffusion_model.label_emb.0.0.weight]
    bad_model_path: logs/2024-07-11T17-03-22_example_training-svd_image/checkpoints/last.ckpt/checkpoint/mp_rank_00_model_states.pt

    # LoRA
    use_lora: False
    lora_config:
      search_class_str: linear
      target_replace_module: null
      r_linear: 16
      r_conv: 16
      loras: null  # path to lora .pt
      # verbose: False
      # dropout_p: 0.0
      # scale: 1.0
      # search_class: both

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.Denoiser
      params:
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.VScalingWithEDMcNoise

    # network_wrapper: sgm.modules.diffusionmodules.wrappers.IdentityWrapper
    # network_wrapper: 
    #   target: sgm.modules.diffusionmodules.wrappers.InterpolationWrapper
    #   params:
    #     im_size: [512, 512] # USER: adapt this to your dataset
    #     n_channels: 4
    #     starting_mask_method: zeros
    #     add_mask: True

    network_config:
      target: sgm.modules.diffusionmodules.video_model.VideoUNet
      params:
        adm_in_channels: 0
        num_classes: sequential
        use_checkpoint: True
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        spatial_transformer_attn_type: softmax-xformers
        extra_ff_mix_layer: True
        use_spatial_context: True
        merge_strategy: learned_with_images
        video_kernel_size: [3, 1, 1]
        fine_tuning_method: null
        audio_cond_method: cross
        additional_audio_frames: 2
        audio_dim: 768
        unfreeze_blocks: [] # Because we changed the input block
        skip_time: true
        reference_to: self

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
        - is_trainable: False
          input_key: cond_frames
          ucg_rate: 0.1
          target: sgm.modules.encoders.modules.ReferenceNet
          params:
            path: /data/home/antoni/code/EchoMimic/pretrained_weights
            cond_type: reference

        - input_key: landmarks
          is_trainable: False
          ucg_rate: 0.1
          target: sgm.modules.encoders.modules.IdentityEncoder
          params:
            cond_type: landmarks

        - input_key: audio_emb
          is_trainable: True
          ucg_rate: 0.2
          target: sgm.modules.encoders.modules.WhisperAudioEmbedder
          params:
            merge_method: mean 
            linear_dim: 1024
            cond_type: crossattn

    first_stage_config:
      target: sgm.models.autoencoder.AutoencodingEngine
      params:
        loss_config:
          target: torch.nn.Identity
        regularizer_config:
          target: sgm.modules.autoencoding.regularizers.DiagonalGaussianRegularizer
        encoder_config: 
          target: sgm.modules.diffusionmodules.model.Encoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1, 2, 4, 4]
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0
        decoder_config:
          target: sgm.modules.autoencoding.temporal_ae.VideoDecoder
          params:
            attn_type: vanilla
            double_z: True
            z_channels: 4
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1, 2, 4, 4]
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0
            video_kernel_size: [3, 1, 1]

    sampler_config:
      target: sgm.modules.diffusionmodules.sampling.EulerEDMSampler
      params:
        num_steps: 25
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.AYSDiscretization
          # params:
          #   sigma_max: 700.0

        guider_config:
          # target: sgm.modules.diffusionmodules.guiders.MultipleCondVanilla
          # params:
          #   scales: [0.1, 0.5, 0.5]
          #   condition_names: [cond_frames, cond_frames_without_noise, audio_emb]
          target: sgm.modules.diffusionmodules.guiders.VanillaCFG
          params:
            scale: 3.5
